apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: klyde

resources:
  - manifests/namespace.yaml
  - manifests/db-statefulset.yaml
  - manifests/db-service.yaml
  - manifests/api-deployment.yaml
  - manifests/api-service.yaml
  - manifests/web-deployment.yaml
  - manifests/web-service.yaml
  - manifests/ingress.yaml
