apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-data
  namespace: twotakeone
  labels:
    app: backend
    app.kubernetes.io/name: backend
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 512Mi
