apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: 2take1
spec:
  replicas: 1
  selector:
    matchLabels: { app: api }
  template:
    metadata:
      labels: { app: api }
    spec:
      containers:
        - name: api
          image: ghcr.io/thev1ndu/2take1-api:latest
          ports:
            - containerPort: 8080
          env:
            - name: DB_ADDR
              value: "db:3306"
            - name: DB_USER
              value: 2take1
            - name: DB_NAME
              value: 2take1
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: 2take1-db-credentials
                  key: password
          readinessProbe:
            httpGet: { path: /api/healthz, port: 8080 }
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet: { path: /api/healthz, port: 8080 }
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests: { memory: "32Mi", cpu: "20m" }
            limits:   { memory: "128Mi", cpu: "250m" }
