apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - manifests/check-deprecated-apis.yaml
  - manifests/disallow-default-namespace.yaml
  - manifests/disallow-latest-tag.yaml
  - manifests/require-labels.yaml
  - manifests/require-pod-requests-limits.yaml
  - manifests/require-probes.yaml
  - manifests/restrict-node-port.yaml
  - manifests/exception-rancher-shell.yaml
