apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: todo-agent
  labels:
    app: redis
    app.kubernetes.io/name: redis
spec:
  type: ClusterIP
  selector: { app: redis }
  ports:
    - port: 6379
      targetPort: 6379
